# Generated by Django 2.1.1 on 2018-10-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='owner',
            new_name='author',
        ),
    ]
